spring.application.name=rickandmortyapi

spring.datasource.url=jdbc:postgresql://localhost:5432/rickandmortydb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

rick-and-morty.api.url=https://rickandmortyapi.com/api